'use client'

import { Area, AreaChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Column, Grid, Tag, Tile } from '@carbon/react'
import { Activity } from '@carbon/icons-react'
import { useDigitalTwin } from './digital-twin-provider'

export default function AnalyticsPage() {
  const { chartData } = useDigitalTwin()

  // Use chartData from the provider. If it's empty, provide a fallback for the axes to render nicely.
  const data = chartData.length ? chartData : [{ time: '--:--', temperature: 0, viscosity: 0, pumpRpm: 0, rodLoad: 0, risk: 0 }]

  return <main id="main-content" className="page-main wellsync-page"><div className="ws-shell"><div className="ws-eyebrow"><Activity size={16} /> DIGITAL TWIN / ANALYTICS</div><div className="ws-title-row"><div><h1>Telemetry analytics</h1><p>Cross-signal trends from the active well telemetry stream.</p></div><Tag type="blue">LIVE SIGNALS</Tag></div><Grid condensed className="ws-analytics-grid"><Column sm={4} md={8} lg={6}><Tile className="ws-panel ws-analytics-panel"><div className="ws-panel-header"><h2>Temperature vs viscosity</h2><Tag type="cool-gray">Dual axis</Tag></div><ResponsiveContainer width="100%" height={280}><LineChart data={data}><CartesianGrid stroke="var(--cds-border-subtle-01)" vertical={false}/><XAxis dataKey="time" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }}/><Tooltip/><Legend/><Line type="monotone" dataKey="temperature" stroke="var(--cds-support-warning)" dot={false} strokeWidth={2}/><Line type="monotone" dataKey="viscosity" stroke="var(--cds-link-primary)" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></Tile></Column><Column sm={4} md={8} lg={6}><Tile className="ws-panel ws-analytics-panel"><div className="ws-panel-header"><h2>RPM vs rod load</h2><Tag type="cool-gray">Mechanical</Tag></div><ResponsiveContainer width="100%" height={280}><AreaChart data={data}><CartesianGrid stroke="var(--cds-border-subtle-01)" vertical={false}/><XAxis dataKey="time" tick={{ fontSize: 11 }}/><YAxis tick={{ fontSize: 11 }}/><Tooltip/><Legend/><Area type="monotone" dataKey="pumpRpm" name="RPM" stroke="var(--cds-link-primary)" fill="var(--cds-link-primary)" fillOpacity={.14}/><Area type="monotone" dataKey="rodLoad" name="Rod Load" stroke="var(--cds-support-warning)" fill="none"/></AreaChart></ResponsiveContainer></Tile></Column><Column sm={4} md={8} lg={12}><Tile className="ws-panel ws-analytics-panel"><div className="ws-panel-header"><h2>Risk score trend</h2><Tag type="green">Decision support</Tag></div><ResponsiveContainer width="100%" height={280}><LineChart data={data}><CartesianGrid stroke="var(--cds-border-subtle-01)" vertical={false}/><XAxis dataKey="time" tick={{ fontSize: 11 }}/><YAxis domain={[0, 100]} tick={{ fontSize: 11 }}/><Tooltip/><Line type="monotone" dataKey="risk" stroke="var(--cds-support-error)" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></Tile></Column></Grid></div></main>
}
